name: "test"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        postgresVersion: ["13", "14"]
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit-openresty"]

    env:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: 127.0.0.1
      DOCKER_POSTGRES_VERSION: ${{ matrix.postgresVersion }}

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@master
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@master

    - name: dependencies
      run: |
        luarocks install busted
        luarocks install luasocket
        luarocks install luasec
        luarocks install moonscript
        luarocks install https://raw.githubusercontent.com/leafo/lua-cjson/master/lua-cjson-dev-1.rockspec
        luarocks install luaossl
        luarocks install cqueues
        [[ "${{ matrix.luaVersion }}" =~ ^5\.[12]$ ]] && luarocks install luabitop || true

    - name: build
      run: |
        luarocks make

    - name: test
      run: |
        busted -o utfTerminal



  test_resty:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        postgresVersion: ["14"]

    env:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: 127.0.0.1
      DOCKER_POSTGRES_VERSION: ${{ matrix.postgresVersion }}

    steps:
    - uses: actions/checkout@master

    - uses: leafo/gh-actions-openresty@main
      with:
        openrestyVersion: "1.19.9.1"

    - uses: leafo/gh-actions-luarocks@master
      with:
        withLuaPath: "/usr/local/openresty/luajit/"

    - name: dependencies
      run: |
        luarocks install busted
        luarocks install moonscript
        luarocks install https://raw.githubusercontent.com/leafo/lua-cjson/master/lua-cjson-dev-1.rockspec
        luarocks install lua-resty-openssl

    - name: build
      run: |
        luarocks make

    - name: test
      run: |
        resty spec/resty_busted.lua

